### ISSUE TITLE
Decimal.slog always return NaN

### ISSUE THREAD

**Issue by 1e1000000** [Patashu/break_eternity.js#109]
It should be return 0 for below example:

![image](https://user-images.githubusercontent.com/54700438/180646432-94a81bf9-093f-498a-99d4-de091eb4a740.jpeg)

and It should be 1:

![image](https://user-images.githubusercontent.com/54700438/180646458-7abe267d-d037-4aad-a07b-28ae10d474f5.jpeg)

**Comment by Patashu** [comment]
It's possible I broke tetrate and slog for small values, I'll check it today

**Comment by 1e1000000** [comment]
It also happen on large number, Decimal.slog("eeeee10",10) return NaN instead of 6

**Comment by Patashu** [comment]
pushed what I think is a fix (it was predictably dumb), but going to hold off on closing the issue until I test other things, I want to make some better unit tests for myself

**Comment by Patashu** [comment]
Ok, I am dumb, I made many problems for myself, it should be fixed now

**Comment by 1e1000000** [comment]
It return 0,1,6 for above examples as it supposed to be.

**Comment by Patashu** [comment]
Great, thanks for reporting quickly!
