### ISSUE TITLE
The next step

### ISSUE THREAD

**Issue by Unexian** [Patashu/break_eternity.js#154]
`Decimal.fromComponents(1,new Decimal("1e5"),100)`

**Comment by alemaninc** [comment]
I'm pretty sure he means to add functionality for 10^^(10^^(2^1024))...

**Comment by Unexian** [comment]
> I'm pretty sure he means to add functionality up to 10^^(10^^(2^1024))...

I mean to be able to use a decimal for layer instead of a number, bringing the max from 10^^1e308 to true infinity.

**Comment by jakub791** [comment]
This isn't the goal of this project

**Comment by 1231234md5** [comment]
#46 
[patashu has an idea bringing the maximum to 10{1.79e308}10, much MUCH larger than 10^^^500. (assuming Decimal can only nest 500 layers),so your idea is only a waste of space.
also you can try omeganum.js, which goes to 10{1000}10.
