### ISSUE TITLE
`new Decimal("(e^x)1")` returns `Decimal` with negative `layer` if `x` is negative

### ISSUE THREAD

**Issue by James103** [Patashu/break_eternity.js#167]
For example, `new Decimal("(e^-8.1)1")` returns a `Decimal` whose `layer` is -8.1.

Similarly, `new Decimal("(e^-22.1)1")` returns a `Decimal` whose `layer` is -22.1.

Both Decimal objects have invalid `layer` values and may not work properly with operations.

**Comment by MathCookie17** [comment]
This is a pretty useless case, seeing as (e^x)1 for any x <= -2 is automatically NaN, but fixed anyway.
