### ISSUE TITLE
Max Value constant

### ISSUE THREAD

**Issue by JamesCarlyleClarke** [Patashu/break_eternity.js#170]
The library would benefit from a max value constant. Is there any reason not to use Number.MAX_VALUE for the layer and mag?

	// Define a high value using MAX_VALUE (possible issues?)
	Decimal.dMaxValue = FC(1, Number.MAX_VALUE, Number.MAX_VALUE);

	// or

	// Define a safe high value using MAX_SAFE_INTEGER
	Decimal.dMaxSafeValue = FC(1, Number.MAX_SAFE_INTEGER, Number.MAX_SAFE_INTEGER);

**Comment by MathCookie17** [comment]
For maxValue, I don't see much reason to make the mag be something other than 1, since at that point the magnitude is meaningless anyway. As for maxSafeValue, since the transition point for layers is at a magnitude of 9e15, I'd make the magnitude there (9e15 - 1) rather than MAX_SAFE_INTEGER (which is slightly larger than 9e15).

I'll consider these for the next update.

**Comment by MathCookie17** [comment]
![image](https://github.com/Patashu/break_eternity.js/assets/74840506/cba3a607-d58e-4c18-a517-f9a0d3d920c6)

**Comment by JamesCarlyleClarke** [comment]
Ah OK. Still, for the absolute absolute maximum, if you simply had to have the highest valid number, does that mean it would be:
```
Decimal.dMaxValue = FC(1, Number.MAX_VALUE, Number.MAX_VALUE);
or
Decimal.dMaxValue = FC(1, Number.MAX_VALUE, 9e15-1);
or
Decimal.dMaxValue = FC(1, 2 ** 53, Number.MAX_VALUE);
or
Decimal.dMaxValue = FC(1, 2 ** 53, 9e15-1);
```
?

**Comment by MathCookie17** [comment]
Decimal.dMaxValue would be FC(1, Number.MAX_VALUE, 9e15-1), and Decimal.dMaxSafeValue would be FC(1, 2 ** 53 - 1, 9e15-1).

**Comment by JamesCarlyleClarke** [comment]
Wonderful, that's extremely helpful, many thanks!
(and while I'm chatting, thanks for the Eternal Notations library, just getting into that!)

**Comment by MathCookie17** [comment]
These constants (Decimal.dLayerMax is the true maximum value, Decimal.dLayerSafeMax is the safe version) have been added in v2.1.0.

**Comment by JamesCarlyleClarke** [comment]
Many thanks, you're awesome!
