### ISSUE TITLE
`Decimal.exp(-1000).eq(Decimal.exp(1000))` is true

### ISSUE THREAD

**Issue by dan-simon** [Patashu/break_eternity.js#33]
They're both high positive numbers (I think they're both what `Decimal.exp(1000)`) should be). `Decimal.exp(-100).eq(Decimal.exp(100))` is false, which makes me think this only happens over infinity. I think this might be at least partially the cause of #32 .

**Comment by Patashu** [comment]
Thanks, this is indeed the fix for both.
