### ISSUE TITLE
isNaN(X) where X is greater than e9e15 return true

### ISSUE THREAD

**Issue by 1e1000000** [Patashu/break_eternity.js#41]
Expected result:
```
isNaN("ee16")
false
```

Actual result:
```
isNaN("ee16")
true
```

I seem it most likely because break_infinity.js

**Comment by Patashu** [comment]
isNan is a built in function, I didn't write it, and "ee16" is indeed not a number. maybe you mean this?

Decimal.fromString("ee16").toNumber()
Infinity
isNaN(Decimal.fromString("ee16").toNumber())
false

**Comment by 1e1000000** [comment]
For actual result, it return true instead

**Comment by Patashu** [comment]
isNaN("ee2") is also true. Try it
