### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by thepaperpilot** [Patashu/break_eternity.js#45]
Dozens of free, unmonetized games already use b_e, but technically this library has no usage license and Patashu could go after those games with C&Ds or worse. Since b_i includes an MIT LICENSE file, I assume this library was intended to also be under the MIT license, but currently its legally not.

**Comment by Patashu** [comment]
yeah this should be under some license that doesn't let me C&D, not that I was ever going to. let me think
